import type { Metadata } from "next";
import { Amaranth, Geist, Geist_Mono, Titillium_Web } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "sonner";
import Sidebar from "@/components/sidebar";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const titillium_Web = Titillium_Web({ weight: "400", subsets: ["latin"] });
export const amaranth = Amaranth({ weight: "400", subsets: ["latin"] });
export const dynamic = 'force-dynamic';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(titillium_Web.className)}>
        <NextTopLoader />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="w-screen h-screen flex custom-scrollbar scroll-smooth">
            <div className="hidden md:flex flex-col">
              <Sidebar />
            </div>
            <div className="w-full">
              <ScrollArea className="h-[100vh] md:h-[100vh]  border-l-2">
                {children}
              </ScrollArea>
            </div>
            {/* <BottomNav /> */}
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
